name: Test Using Mocha

on: [push]

jobs:
  test:
    runs-on: ubuntu-lates
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install Dependencies
        run: npm install 
      - name: Run Tests
        run: npm run test
      - run: echo: "All tests passed"